USE [master]
GO

/****** Object:  Database [Article1]    Script Date: 7/28/2024 10:41:42 AM ******/
CREATE DATABASE [Article1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shop', FILENAME = N'F:\Github\Article-Branch\Databae\Article1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shop_log', FILENAME = N'F:\Github\Article-Branch\Databae\Article1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Article1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Article1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Article1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Article1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Article1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Article1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Article1] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Article1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Article1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Article1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Article1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Article1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Article1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Article1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Article1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Article1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Article1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Article1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Article1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Article1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Article1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Article1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Article1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Article1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Article1] SET  MULTI_USER 
GO

ALTER DATABASE [Article1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Article1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Article1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Article1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Article1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Article1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Article1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Article1] SET  READ_WRITE 
GO


